In [2]:
import numpy as np
import pandas as pd

In [3]:
l = ["Vikas",2,3+5j]

In [4]:
l1 = [1,2,23,4,33,23,23]
type(l1)

list

In [6]:
l1 = np.array(l1)

In [7]:
type(l1)

numpy.ndarray

In [9]:
ls = np.array(l)
type(ls)

numpy.ndarray

In [11]:
l2 = np.matrix(l1)

In [13]:
l1.ndim

1

In [14]:
l2.ndim

2

In [15]:
np.array([l1])

array([[ 1,  2, 23,  4, 33, 23, 23]])

In [16]:
type(np.array([l1]))

numpy.ndarray

In [17]:
np.array([l1]).ndim

2

In [18]:
np.array([[l1]])

array([[[ 1,  2, 23,  4, 33, 23, 23]]])

In [19]:
np.array([[l1]]).ndim

3

In [21]:
r = range(1,10)
r

range(1, 10)

In [22]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.ones((3,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.random.random((3,3))

array([[0.84348426, 0.1358306 , 0.38985095],
       [0.53630988, 0.73571811, 0.34086117],
       [0.13389998, 0.16168506, 0.09270183]])

In [30]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
print("The End")

The End
