In [1]:
import numpy as np
import pandas as pd

In [4]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [5]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
np.arange(10,dtype=np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [7]:
np.arange(10,dtype=np.int64)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10,dtype=np.float32)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [9]:
np.arange(10,dtype=np.float64)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
a3 = np.arange(12,dtype=np.float32).reshape(3,4)
a3

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [17]:
a3 = np.arange(12,dtype=np.float32).reshape(2,6)
a3

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)

In [18]:
a3 = np.arange(8,dtype=np.float32).reshape(2,2,2)
a3

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]], dtype=float32)

In [19]:
a3.ndim

3

In [20]:
a3.size

8

In [21]:
a3**2

array([[[ 0.,  1.],
        [ 4.,  9.]],

       [[16., 25.],
        [36., 49.]]], dtype=float32)

In [22]:
a3.itemsize

4

In [25]:
a3.T

array([[[0., 4.],
        [2., 6.]],

       [[1., 5.],
        [3., 7.]]], dtype=float32)

In [27]:
arr = np.random.randint(0,10,(3,3))

In [28]:
arr

array([[4, 3, 6],
       [7, 3, 3],
       [2, 7, 1]], dtype=int32)

In [29]:
arr.T

array([[4, 7, 2],
       [3, 3, 7],
       [6, 3, 1]], dtype=int32)

# **Methods and Function**

In [30]:
arr1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr1.sum()

np.int64(45)

In [32]:
sum(arr1)

array([12, 15, 18])

In [33]:
arr1.min()

np.int64(1)

In [34]:
np.std(arr1)

np.float64(2.581988897471611)

In [35]:
np.var(arr1)

np.float64(6.666666666666667)

In [36]:
np.cumsum(arr1)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [37]:
np.cumsum(arr1,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]])

In [38]:
np.argmax(arr1)

np.int64(8)

In [39]:
np.argmin(arr1)

np.int64(0)

In [40]:
np.transpose(arr1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [42]:
arr1**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [43]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [44]:
arr2 = np.array([
    [7,8,9],
    [10,11,12]
])

In [45]:
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [46]:
arr1 -arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [47]:
arr1 * arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [48]:
arr1 / arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [50]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])

In [52]:
arr3 = np.array([
    [1,2],
    [4,5],
    [7,8]
])

In [53]:
arr1 @ arr3

array([[30, 36],
       [66, 81]])

In [54]:
np.dot(arr1,arr2)

array([[30, 36],
       [66, 81]])

In [55]:
np.matmul(arr1,arr2)

array([[30, 36],
       [66, 81]])

In [59]:
a1 = np.array([1,23,43,3232,4443,4332])

In [60]:
a1[3]

np.int64(3232)

In [61]:
a1[0]

np.int64(1)

In [62]:
a1[1:3]

array([23, 43])

In [64]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr1[1,2]

np.int64(6)

In [66]:
arr1[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [68]:
a1

array([   1,   23,   43, 3232, 4443, 4332])

In [69]:
for i in a1:
    print(i)

1
23
43
3232
4443
4332


In [71]:
for row in arr1:
    for e in row:
        print(e,end=" ")
    print()

1 2 3 
4 5 6 


In [72]:
for i in np.nditer(arr1):
    print(i, end=" ")

1 2 3 4 5 6 

In [73]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
print("The End")

The End
